### ISSUE TITLE
memory read

### ISSUE THREAD

**Issue by jhy213** [SNU-ARC/2023_fall_comarch_PA3#13]
memory.v 파일에서
assign read_data = ((address & (~MEM64_BITMASK)) || write_enable) ? 64'h0 : data[address[7:3]];
정상적인 address에 대해서는 (address & (~MEM64_BITMASK)) 값이 0이 되고
load instruction에서 write_enable이 0이니까
read_data가 안되는 것 같아 질문드립니다.

**Comment by kjh0615** [comment]
말씀하신 대로 정상적인 address에서는 address & (~MEM64_BITMASK)의 값이 0이 되고,

write_enable의 값도 0이니 

두 값을 OR 연산한 값도 0이 되어, 3항 연산자 조건 중 FALSE 조건에 해당 되어 read_data = data[address[7:3]] 구문이 실행되게 됩니다.

* 3항 연산자

조건 ? 참일 때 실행 하는 내용 : 거짓일 때 실행하는 내용

감사합니다.

**Comment by jhy213** [comment]
앗 제가 잘못 봤네요 감사합니다!
