### ISSUE TITLE
synthesis, implemtation

### ISSUE THREAD

**Issue by jhy213** [SNU-ARC/2023_fall_comarch_PA3#15]
run simulation해서 register값이랑 memory값은 정상적으로 저장되었는데
run synthesis, run implemtation하면 
'[Synth 8-4445] could not open $readmem data file 'perf2.dat'; please make sure the file is added to project and has read permission, ignoring'
'unable to resolve alu'
'failed synthesizing module 'pipeline_ctl'등의 에러가 나서
혹시 run synthesis, run implemtation했을 때 에러가 나면 안되는 건지 질문드립니다.

**Comment by Jong25** [comment]
run synthesis와 run implementation이 작동하지 않는 것은 정상이니 걱정하지 않으셔도 됩니다.

**Comment by jhy213** [comment]
넵 감사합니다!
