### ISSUE TITLE
BEQ 구현 관련

### ISSUE THREAD

**Issue by mingkyun** [SNU-ARC/2023_fall_comarch_PA3#16]
안녕하세요. https://github.com/SNU-ARC/2023_fall_comarch_PA3/issues/9에서 비슷한 질문이 있었는데, Problem 1에서 요구하는 MEM 단계 branch control unit을 따로 구현할 필요 없이 처음부터 ID stage에서 비교하는 것으로 구현하고, ID stage를 기준으로 stall과 hazard handling, static branch predictor를 구현해도 된다는 의미인지 궁금합니다. 이렇게 되면 problem1을 안 푸는(?) 것 같아서 제가 제대로 이해한 게 맞는지 궁금합니다.

**Comment by kjh0615** [comment]
넵 맞습니다.

BEQ를 처음부터 ID Stage로 구현하실 수 있다면, Mem Stage 구현은 하지 않으셔도 괜찮습니다.

다만 Perf1.dat Test Bench의 경우는 Mem Stage/ID Stage Branch 구현 모두 만점을 받을 수 있는 기준이며,

Perf3.dat Test Bench의 경우 ID Stage Branch로 구현해야만 만점을 받을 수 있습니다.

참고 부탁드립니다.
