### ISSUE TITLE
perf3 performance

### ISSUE THREAD

**Issue by SeongjunJo** [SNU-ARC/2023_fall_comarch_PA3#17]
안녕하세요, PA3 pdf를 보면 perf3.dat의 수행시간은 부등호가 있는 perf1과 달리 980ns로 고정되어 있는데요, 혹시 problem 3를 구현하면 980ns만 정답이 되는 것인지 궁금합니다. console의 출력 값과 직접 계산해본 예상 값이 같고, 하드 코딩은 없었다고 생각하는데 980ns보다 짧게 나와서, 이 경우가 가능한 것인지 답변 해주실 수 있는 범위 내에서 알려주신다면 감사하겠습니다.

**Comment by 99DHL** [comment]
안녕하세요 조교 이동현입니다. 이번 과제의 의도는 저희가 제시한 디자인대로 구현하는 것이고, 그 디자인대로 구현했을 때 980ns가 나와야 하기 때문에 다른 값은 허용하지 않을 계획입니다. 만약 저희가 제시한 것 이외에 추가적인 어떤 최적화를 통해 더 빠른 값이 나온 것이라면, 그 부분은 제거하고 제출하시는게 좋을 것 같습니다. 만약, 저희가 제시한 디자인대로 구현했을 때도 980ns보다 빠른 값이 나오는 것이 맞다고 생각하시면 아래 이메일로 손으로 계산했을 때 어떻게 그 cycle값이 나왔는지 설명을 보내주시면 감사하겠습니다.
eudh1206@snu.ac.kr
