### ISSUE TITLE
Correctness 질문

### ISSUE THREAD

**Issue by mingkyun** [SNU-ARC/2023_fall_comarch_PA3#19]
안녕하세요. 이번 과제에서는 구현이 맞게 됐는지 어떻게 확인할 수 있는지 궁금합니다. 현재 어셈블리 코드를 직접 해석하고 예상한 대로 흘러가고 있는지 waveform을 통해 확인하고 있는데, 이 방법밖에 없는지 궁금합니다.

추가로 구현에 따라 중간중간에 레지스터 값 차이가 살짝 존재할 수도 있을 것 같은데 (전부 반 clock씩 밀리는 등) 종료 시점에만 각 레지스터에 맞는 숫자가 들어가 있으면 되는지 궁금합니다.

**Comment by 99DHL** [comment]
안녕하세요. 현재 저희 과제 코드에서는 각 레지스터와 메모리 값이 변할 때마다 log를 찍도록 구현되어 있습니다. correctness를 체크하는 테스트벤치는 그 log가 정답과 동일하면 만점이고, performance를 체크하는 테스트벤치의 경우 log가 정답과 동일하고, 출력되는 cycle수도 동일해야 만점이 주어집니다.

**Comment by mingkyun** [comment]
답변 감사합니다. 추가 질문이 있는데, 현재 제 구현에서 reg_file 모듈을 스켈레톤에서 제공한 것 외에 한 번 더 사용중입니다. 그래서 현재 한 레지스터의 값이 두 번씩 출력되는 상황인데, 이렇게 구현하면 correctness 기준을 만족시키지 못 하는 것일까요?

**Comment by 99DHL** [comment]
현재 reg_file 모듈은 write signal이 들어갈 때만 register에 값을 쓰고, log를 print하도록 구현되어 있습니다. register값이 두 번 출력된다는 것은 register에도 값을 2번 쓴다는 것인데 이것은 정상적인 구현이 아닌 것 같습니다.
