### ISSUE TITLE
inst_decoder에서 imm64 저장 관련 문의

### ISSUE THREAD

**Issue by parkchaehyun** [SNU-ARC/2023_fall_comarch_PA3#2]
inst_decoder의 50번째 줄에 //1100011(S): Beq, Bne, Blt, Bge, Bltu, Bgeu
라고 되어 있고 밑에 imm64도 B-type에 대한 고려를 안 하고 있는데
imm64를 저장할 때 B-type에 대한 구현을 저희가 따로 추가하는 것이 의도인지, 오타로 인해 빠져있는 건지 궁금합니다

**Comment by parkchaehyun** [comment]
감사합니다!

**Comment by minseo25** [comment]
안녕하세요inst_decoder.v 46-47번째 라인에 slt, sltu, sra, slti, sltiu 명령어들이 적혀있는데, PA3.pdf에서는 언급되지 않은 명령어들 같습니다
해당 명령어들에 대한 처리도 control.v 에서 해야 하나요?

**Comment by kjh0615** [comment]
안녕하세요 과제에서 언급한 부분만 구현해주시면 됩니다 나머지는 참고용으로 주석달아놓은 것 입니다.

감사합니다

2023년 10월 31일 (화) 오후 11:09, minseo25 ***@***.***>님이 작성:

**Comment by minseo25** [comment]
답변 감사합니다
