### ISSUE TITLE
branch instruction관련 질문

### ISSUE THREAD

**Issue by kay1918** [SNU-ARC/2023_fall_comarch_PA3#20]
안녕하세요, 코드를 짜는 중에 헷갈려서 질문합니다

beq x7, x0, 4라는 코드가 sample.s에 있다면
branch가 taken된 경우 PC = PC + (4<<1)로 두 instruction앞이 실행되는 것이 맞을까요?
아니면 이미 PC에는 PC+4값이 있으므로 세 instruction앞이 실행되는 것일까요?

**Comment by kjh0615** [comment]
안녕하세요 TA 김정훈입니다.

beq x7,x0,4
Instruction 1
Instruction 2
...

이 있다면, Instruction 2 (두 Instruction 앞)가 실행되는 것이 맞습니다.
