### ISSUE TITLE
Performance 관련 질문

### ISSUE THREAD

**Issue by ziseoklee** [SNU-ARC/2023_fall_comarch_PA3#21]
perf1, 2, 3.dat을 실행했을 때 과제 PDF에 표기된 시간보다 빠르게 실행되면서 정확한 결과가 나와도 괜찮은지 궁금합니다.

perf2.dat이나 perf3.dat을 실행했을 때 정확히 200ns, 980ns여야 하는 것인지, 더 빨리 실행되어도 괜찮은지 (추가적인 최적화를 통해) 알고 싶습니다.

**Comment by 99DHL** [comment]
안녕하세요. 이번 과제의 의도는 저희가 제시한 디자인대로 구현하는 것이고, 그 디자인대로 구현했을 때 980ns가 나와야 하기 때문에 다른 값은 허용하지 않을 계획입니다. 만약 저희가 제시한 것 이외에 추가적인 어떤 최적화를 통해 더 빠른 값이 나온 것이라면, 그 부분은 제거하고 제출하시는게 좋을 것 같습니다.
Similar issue in #17
