### ISSUE TITLE
finish 작동

### ISSUE THREAD

**Issue by fyoon46** [SNU-ARC/2023_fall_comarch_PA3#22]
branch.dat에 대해서 돌려봤을 때, 결과값은 잘 나오지만, finish가 1이 안되어 빨리 안끝나는 것 같습니다. halt가 1이 되면 memory.v의 구현에 따라 $finish가 호출되어야 하는데, 왜 안되는지에 대해 질문드립니다.
![KakaoTalk_Photo_2023-11-08-15-59-42](https://github.com/SNU-ARC/2023_fall_comarch_PA3/assets/52787727/e403480c-b23e-425e-b292-2e3c05c5da46)

**Comment by kjh0615** [comment]
안녕하세요 TA 김정훈입니다.

현재 Upload 되어 있는 Test bench의 경우, 

모두 Halt Instruction을 수행할 수 있는 형태로 구현이 되어있습니다.

Branch decision을 정상적으로 구현한 것인지 확인 부탁드립니다.

#20 을 참조부탁드립니다.
