### ISSUE TITLE
Helper program 관련 질문

### ISSUE THREAD

**Issue by ziseoklee** [SNU-ARC/2023_fall_comarch_PA3#23]
Helper program으로 새로운 test.dat 파일을 만들어서 실행해보았는데, waveform을 확인해보니 rom64의 data에 전부 XXX 값들로 아예 읽히지 않는 것을 확인했습니다.

주어진 branch.dat 같은 파일들과 data.dat은 잘 읽히는데 새로 만든 파일은 readmemh가 왜 안 되는지 궁금합니다.

**Comment by kjh0615** [comment]
안녕하세요 TA 김정훈입니다.
Valid instruction을 사용하지 않으면 잘못된 바이너리 파일이 생성 될 수 있습니다. 어셈블리 파일(.s) 올려주시면 검토해보겠습니다.

**Comment by kjh0615** [comment]
안녕하세요 TA 김정훈입니다.

Windows 환경에서 riscv assembler를 사용할 때 일부 잘못 변환 되는 현상을 확인했습니다.

혹시 Windows 환경 쓰시는 중인지 문의드립니다.

감사합니다.
