### ISSUE TITLE
sample2.s 관련 질문

### ISSUE THREAD

**Issue by WHJang-0421** [SNU-ARC/2023_fall_comarch_PA3#3]
안녕하세요. `Testbench`의 `sample2.s` 파일에서 `beq`의 모든 immediate 값이 절반으로 줄어야 할 것 같습니다. 현재는 `beq`이 실행되면 주어진 프로그램 바깥으로 pc가 이동하게 됩니다.

**Comment by Jong25** [comment]
안녕하세요, 해당 내용 확인하였고, 수정된 sample2.s와 sample2.dat이 담긴 Testbench.tar 파일을 올려두었습니다. git pull을 통해 확인 가능합니다.
다만 조교의 환경에서 테스트를 해보지 않았다는 점 말씀드리며, 내일 테스트 후 전체 공지하도록 하겠습니다.
감사합니다.

**Comment by kjh0615** [comment]
안녕하세요, TA 김정훈입니다. 현재 수정된 Test bench File로 정상수행되는 것 확인했습니다.

감사합니다.
