### ISSUE TITLE
sample data access 관련 질문

### ISSUE THREAD

**Issue by kimhaneal11** [SNU-ARC/2023_fall_comarch_PA3#5]
안녕하세요. 새 프로젝트를 만들고 simulation source를 import하는 데에 있어 어려움을 겪고 있어 질문드립니다.

![제목 없음](https://github.com/SNU-ARC/2023_fall_comarch_PA3/assets/84558752/856ad7f5-f2f9-434c-86f5-dbc5ac5c41ae)

사진처럼 source를 불러오려고 할 때 '.dat' 파일을 가져올 수가 없던데, 혹시 제가 setup 자료를 잘못 이해한 것인가요?

**Comment by 99DHL** [comment]
안녕하세요. 화면에 보이는 Files of type을 All files로 설정하시면 dat file을 추가하실 수 있습니다.

**Comment by kimhaneal11** [comment]
앗 all files을 못봤네요..ㅠ 감사합니다!
