### ISSUE TITLE
Beq 관련 질문

### ISSUE THREAD

**Issue by yennieday2** [SNU-ARC/2023_fall_comarch_PA3#8]
다음 instruction으로 넘어갈 때 pc + offset <<1 해서 넘어가는 것 맞을까요?
beq x7, x3, 14면 PC+14*2로 분기하는 방식이요. 
저렇게 알고 있는데 잘 작동하지 않아서 혹시나 개념이 틀린 걸까 하여 질문 드립니다.

**Comment by yennieday2** [comment]
sample2.s와 비슷한 문제가 branch.s에서도 있는 것 같습니다

**Comment by Jong25** [comment]
말씀하신대로 offset * 2만큼 pc에 더하여 작동하도록 되어있어 beq x7, x3, 14인 경우 7 instruction 이후로 뛰게 되고, branch.s에서 예시를 드신 것 같은데 바로 halt로 뛰게 됩니다.
문제가 해결되지 않으면 추가 질문해주시기 바랍니다.

**Comment by kjh0615** [comment]
안녕하세요 TA 김정훈입니다.

추가 부연 설명을 드리자면,

offset << 1 의 동작은 instruction을 machine language로 변환할 때 발생합니다. (즉 dat 파일에는 이미 변환된 형태입니다)

참고 부탁드립니다.
