### ISSUE TITLE
beq 구현 관련 질문

### ISSUE THREAD

**Issue by minseo25** [SNU-ARC/2023_fall_comarch_PA3#9]
안녕하세요.
Problem 3에서 branch decision을 MEM 단계에서 ID 단계로 옮기게 되는데, 이 때 MEM 단계의 branch decision 구현 사항을 그대로 남겨두어야 하나요? 아니면 stall을 최소화하는 방향으로 branch decision을 ID 단계에서만 구현하면 될까요?

'Should implement **additional** forwarding and hazard detection hardware' 이 부분에서 헷갈려서 질문 드립니다.

**Comment by kjh0615** [comment]
안녕하세요 TA 김정훈입니다.

Problem 3에서는 Mem stage branch decision 관련 구현이 제거되어도 상관 없습니다. (다만 동작상 문제가 없어야 합니다)

말씀해주신대로 stall을 최소화하는 방향으로 Branch Decision을 ID Stage에서 구현하고, 변경에 따른 forwarding Logic과 hazard detection hardware를 구현하라는 뜻입니다.

**Comment by minseo25** [comment]
넵 감사합니다!
